### ISSUE TITLE
bug: aws-vpc-no-public-ingress-sgr reported for specific IPs

### ISSUE THREAD

**Issue by acdha** [aquasecurity/defsec#460]
I thought this was a regression of aquasecurity/tfsec#1119 but it turns out to be even broader. A SG ingress rule which mentions only specific IPs will trigger aws-vpc-no-public-ingress-sgr as a CRITICAL using tfsec v1.15.1:

```hcl
resource "aws_security_group_rule" "allow_partner_rsync" {
  type              = "ingress"
  security_group_id = aws_security_group.….id
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  cidr_blocks = [
    "1.2.3.4/32",
    "4.5.6.7/32",
  ]
}
```

In my real code every CIDR block is a /32 which seems incompatible with the documentation's description:
> An ingress security group rule allows traffic from /0.

**Comment by liamg** [comment]
This does not appear to trigger with latest tfsec - looks to have been fixed elsewhere.

**Comment by acdha** [comment]
I confirmed this bug is still present in tfsec v1.26.3 after my ignore comments all expired this month. This affects usage with both variables and with lists of IP addresses — the widest CIDR range in that list is a /16 which is also shown in the example in the documentation so I'd expect it to work.
